function ddq = autofun_ddq_lagr_ballbot2D(theta,phi,dtheta,dphi,tau,M_body,M_ball,I_body,I_ball,L,r,grav)
%AUTOFUN_DDQ_LAGR_BALLBOT2D
%    DDQ = AUTOFUN_DDQ_LAGR_BALLBOT2D(THETA,PHI,DTHETA,DPHI,TAU,M_BODY,M_BALL,I_BODY,I_BALL,L,R,GRAV)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Aug-2017 17:30:31

t2 = L.^2;
t3 = r.^2;
t4 = M_body.^2;
t5 = cos(phi);
t6 = sin(phi);
t7 = dphi.^2;
t8 = I_ball.*I_body;
t9 = t2.*t3.*t4;
t10 = I_ball.*M_body.*t2;
t11 = I_body.*M_ball.*t3;
t12 = I_body.*M_body.*t3;
t13 = M_ball.*M_body.*t2.*t3;
t14 = t5.^2;
t15 = t8+t9+t10+t11+t12+t13-t2.*t3.*t4.*t14;
t16 = 1.0./t15;
t17 = I_ball.*tau;
t18 = M_ball.*t3.*tau;
t19 = M_body.*t3.*tau;
t20 = t2.*t3.*t4.*t5.*t6.*t7;
ddq = [t16.*(t17+t18+t19+t20+I_body.*tau+M_body.*t2.*tau-I_ball.*L.*M_body.*grav.*t6-L.*M_body.*r.*t5.*tau.*2.0-L.*grav.*t3.*t4.*t6+grav.*r.*t2.*t4.*t5.*t6-L.*M_ball.*M_body.*grav.*t3.*t6-I_body.*L.*M_body.*r.*t6.*t7-L.*r.*t2.*t4.*t6.*t7);-t16.*(t17+t18+t19+t20-I_ball.*L.*M_body.*grav.*t6-L.*M_body.*r.*t5.*tau-L.*grav.*t3.*t4.*t6-L.*M_ball.*M_body.*grav.*t3.*t6)];
