function [p_ball,p_body] = autofun_kinematics_ballbot2D(theta,phi,dtheta,dphi,tau,M_body,M_ball,I_body,I_ball,L,r,grav)
%AUTOFUN_KINEMATICS_BALLBOT2D
%    [P_BALL,P_BODY] = AUTOFUN_KINEMATICS_BALLBOT2D(THETA,PHI,DTHETA,DPHI,TAU,M_BODY,M_BALL,I_BODY,I_BALL,L,R,GRAV)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Aug-2017 17:30:31

t2 = phi+theta;
t3 = r.*t2;
p_ball = [t3;0.0];
if nargout > 1
    p_body = [t3-L.*sin(phi);L.*cos(phi)];
end
