function ddq = autofun_ddq_lagr_ballbot2D(theta,phi,dtheta,dphi,tau,M_body,M_ball,I_body,I_ball,L,r,grav)
%AUTOFUN_DDQ_LAGR_BALLBOT2D
%    DDQ = AUTOFUN_DDQ_LAGR_BALLBOT2D(THETA,PHI,DTHETA,DPHI,TAU,M_BODY,M_BALL,I_BODY,I_BALL,L,R,GRAV)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-Dec-2020 14:02:12

t2 = cos(phi);
t3 = sin(phi);
t4 = I_ball.*tau;
t5 = L.^2;
t6 = M_body.^2;
t7 = dphi.^2;
t8 = r.^2;
t9 = I_ball.*I_body;
t10 = t2.^2;
t11 = I_ball.*M_body.*t5;
t12 = I_body.*M_ball.*t8;
t13 = I_body.*M_body.*t8;
t14 = M_ball.*t8.*tau;
t15 = M_body.*t8.*tau;
t16 = I_ball.*L.*M_body.*grav.*t3;
t17 = M_ball.*M_body.*t5.*t8;
t19 = L.*M_ball.*M_body.*grav.*t3.*t8;
t20 = t5.*t6.*t8;
t21 = L.*grav.*t3.*t6.*t8;
t18 = -t16;
t22 = -t19;
t23 = -t21;
t24 = t10.*t20;
t26 = t2.*t3.*t7.*t20;
t25 = -t24;
t27 = t9+t11+t12+t13+t17+t20+t25;
t28 = 1.0./t27;
ddq = [t28.*(t4+t14+t15+t18+t22+t23+t26+I_body.*tau+M_body.*t5.*tau+L.*M_body.*r.*t2.*tau.*2.0+L.^3.*r.*t3.*t6.*t7-grav.*r.*t2.*t3.*t5.*t6+I_body.*L.*M_body.*r.*t3.*t7);-t28.*(t4+t14+t15+t18+t22+t23+t26+L.*M_body.*r.*t2.*tau)];
