function dx = autofun_dx_ode_ballbot2D(theta,phi,dtheta,dphi,tau,M_body,M_ball,I_body,I_ball,L,r,grav)
%AUTOFUN_DX_ODE_BALLBOT2D
%    DX = AUTOFUN_DX_ODE_BALLBOT2D(THETA,PHI,DTHETA,DPHI,TAU,M_BODY,M_BALL,I_BODY,I_BALL,L,R,GRAV)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-Dec-2020 14:02:12

t2 = cos(phi);
t3 = sin(phi);
t4 = I_ball.*grav;
t5 = L.^2;
t6 = M_body.^2;
t7 = dphi.^2;
t8 = r.^2;
t9 = I_ball.*I_body;
t10 = t2.^2;
t11 = M_ball.*t8;
t12 = M_body.*t8;
t13 = I_ball.*M_body.*t5;
t19 = t5.*t6.*t8;
t14 = I_body.*t11;
t15 = I_body.*t12;
t16 = grav.*t11;
t17 = grav.*t12;
t18 = M_body.*t5.*t11;
t20 = L.*t2.*t7.*t12;
t22 = t10.*t19;
t21 = -t20;
t23 = -t22;
t24 = t9+t13+t14+t15+t18+t19+t23;
t25 = 1.0./t24;
dx = [dtheta;dphi;t25.*tau.*(I_ball+I_body+t11+t12+M_body.*t5+L.*M_body.*r.*t2.*2.0)-L.*M_body.*t3.*t25.*(t4+t16+t17+t21-I_body.*r.*t7-M_body.*r.*t5.*t7+L.*M_body.*grav.*r.*t2);-t25.*tau.*(I_ball+t11+t12+L.*M_body.*r.*t2)+L.*M_body.*t3.*t25.*(t4+t16+t17+t21)];
