function [ dx ] = ballbot3D_noYaw_dyn_wrap(t,x,u,params)

    % Unpack state variables
    theta_x = x(1);
    theta_y = x(2);
    gamma = x(3); %phi_x
    beta = x(4); %phi_y
    dtheta_x = x(5);
    dtheta_y = x(6);
    dgamma = x(7); %dphi_x
    dbeta = x(8); %dphi_y
          
    % Unpack control inputs
    tau_x = u(1);
    tau_y = u(2);
    
%     dx =  autofun_ddq_ode_ballbot3D_noYaw(theta_x,theta_y,gamma,beta,dtheta_x,dtheta_y,dgamma,dbeta,...
%                                           tau_x,tau_y,...
%                                           params.M_body,params.M_ball,...
%                                           params.Ixx_body,params.Iyy_body,params.Izz_body,...
%                                           params.Ixx_ball,params.Iyy_ball,params.Izz_ball,...
%                                           params.L,params.r,params.grav);
% 
    dx =  autofun_ddq_ode_ballbot3D_noYaw(theta_x,theta_y,gamma,beta,dtheta_x,dtheta_y,dgamma,dbeta,...
                                          tau_x,tau_y,...
                                          params.M_body,params.M_ball,...
                                          params.Ixx_body,params.Iyy_body,params.Izz_body,...
                                          params.Ixx_ball,...
                                          params.L,params.r,params.grav);
    
end

