function [V_eps,LfVeps,LgVeps] = autofun_CLFLieDerv_ballbot2D_IO_PD(theta,phi,dtheta,dphi,phi_d,dphi_d,epsilon)
%AUTOFUN_CLFLIEDERV_BALLBOT2D_IO_PD
%    [V_EPS,LFVEPS,LGVEPS] = AUTOFUN_CLFLIEDERV_BALLBOT2D_IO_PD(THETA,PHI,DTHETA,DPHI,PHI_D,DPHI_D,EPSILON)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Aug-2017 18:20:59

t2 = conj(dphi);
t3 = sqrt(3.0);
t4 = conj(phi);
t5 = dphi-dphi_d;
t6 = dphi_d-t2;
t7 = phi_d-t4;
t8 = 1.0./epsilon.^2;
t9 = phi-phi_d;
V_eps = -t9.*(dphi_d-t2+t3.*t7)-t5.*(phi_d-t4+t3.*t6);
if nargout > 1
    t10 = 1.0./epsilon;
    LfVeps = -t5.*(t6.*t10.*2.0+t3.*t7.*t8)-t3.*t6.*t8.*t9;
end
if nargout > 2
    LgVeps = -t3.*(dphi_d.*2.0-t2.*2.0)-t10.*(phi_d.*2.0-t4.*2.0);
end
