function [LgLfh,Lf2h] = autofun_LieDerv_ballbot2D_IO_PD(theta,phi,dtheta,dphi,phi_d,dphi_d)
%AUTOFUN_LIEDERV_BALLBOT2D_IO_PD
%    [LGLFH,LF2H] = AUTOFUN_LIEDERV_BALLBOT2D_IO_PD(THETA,PHI,DTHETA,DPHI,PHI_D,DPHI_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Aug-2017 18:20:59

t2 = cos(phi);
t3 = t2.^2;
t4 = t3.*1.423452879810162e1;
t5 = t4-2.318304938091145e1;
t6 = 1.0./t5;
LgLfh = -t6.*(t2.*3.772867450375327-6.234128445252728e-1);
if nargout > 1
    Lf2h = t6.*sin(phi).*(dphi.^2.*t2.*3.993128848089195e-1-6.115680004792926).*3.564755694e1;
end
