function [psi0,psi1] = autofun_psi_ballbot2D_IO_PD(theta,phi,dtheta,dphi,phi_d,dphi_d,c3,epsilon)
%AUTOFUN_PSI_BALLBOT2D_IO_PD
%    [PSI0,PSI1] = AUTOFUN_PSI_BALLBOT2D_IO_PD(THETA,PHI,DTHETA,DPHI,PHI_D,DPHI_D,C3,EPSILON)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    26-Aug-2017 18:20:59

t2 = 1.0./epsilon;
t3 = dphi-dphi_d;
t4 = conj(phi);
t5 = sqrt(3.0);
t6 = conj(dphi);
t7 = dphi_d-t6;
t8 = phi_d-t4;
t9 = 1.0./epsilon.^2;
t10 = phi-phi_d;
psi0 = -t3.*(t2.*t7.*2.0+t5.*t8.*t9)-c3.*t2.*(t10.*(dphi_d-t6+t5.*t8)+t3.*(phi_d-t4+t5.*t7))-t5.*t7.*t9.*t10;
if nargout > 1
    psi1 = -t5.*(dphi_d.*2.0-t6.*2.0)-t2.*(phi_d.*2.0-t4.*2.0);
end
